title: Welcome at @earth4723 # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
 Hello, we're EARTH 4723, and we are from <a href= "https://www.instagram.com/tecmilenio_puebla/"> Tecmilenio University, Puebla </a> we participate in FIRST Robotics Competition (FRC)<br> <br>

theme: jekyll-theme-minimal
