title: Welcome at @earth4723 # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hello, we're EARTH 4723, and I'm from <a href= "https://www.instagram.com/p/CClVytAF1oy/">  Puebla 🇲🇽.  </a>  I process medical images at INAOE. <br> <br>
 
 Keywords: 
 Medical imaging,
 Image processing and analysis,
 Machine learning,
 Coffee,
 Computer vision,
 Digital signal precessing,
 Deep learning,
 Robotics,
 <a href= "https://twitter.com/Jose_Rangel_M/status/1164566151914876928?s=20"> Digital Signal Group, </a> 
 Biophotonics,
 Matlab and Python,
 <a href= "https://twitter.com/Friscolt/status/1120074887815520256?s=20"> Biosignal lab! </a> 

theme: jekyll-theme-minimal
